
@baseurl = http://localhost:3000

### Mengambil data user dari GitHub
GET {{baseurl}}/subbidang

### redirect to elysia
GET {{baseurl}}/toElysia

### tes post body
POST {{baseurl}}/user
Content-Type: application/json

{
    "name": "Fiqh",
    "age": 12
}

### profile cookie
GET {{baseurl}}/profile

### sign up new user or account
POST {{baseurl}}/api/auth/sign-up/email
Content-Type: application/json

{
    "name": "Admin Apotek",
    "email": "fiqihalfito.dev@gmail.com",
    "password": "123456"
}

### health check
GET {{baseurl}}/api/auth/ok