import { eq } from "drizzle-orm";
import { createAuthClient } from "better-auth/client";
import { db } from "../connect";
import {
    applicationServicesTable,
    departementsTable,
    helpTopicsTable,
    organizationsTable,
    subDepartmentsTable,
    subTeamsTable,
    teamLeadersTable,
    teamMembersTable,
    teamsTable,
    usersTable,
} from "../schema";
import { truncateAll } from "./truncate-data";

const authClient = createAuthClient({
    baseURL: "http://localhost:3000/auth/api",
});

const DEFAULT_PASSWORD = "12345678";

// =========================================================================
// Users
// signed up via authClient.signUp.email (creates user + account together).
// user_id is generated by Better Auth, not hardcoded — we fetch it back
// from the DB by email right after sign-up.
// =========================================================================

// each entry's "key" matches the USER.<key> references used later in this
// file (departements, sub_departments, team_leaders, team_members)
const userSignUpData: { key: string; name: string; email: string }[] = [
    { key: "hermawanAsmoko", name: "Hermawan Asmoko", email: "hermawan.asmoko@iconpln.co.id" },
    { key: "fulanVpLain", name: "Fulan VP Lain", email: "fulan.vp.lain@iconpln.co.id" },
    { key: "yoraYunita", name: "Yora Yunita", email: "yora.yunita@iconpln.co.id" },
    { key: "christland", name: "Christland P. Simatupang", email: "christland.p.simatupang@iconpln.co.id" },
    { key: "andrian", name: "Andrian", email: "andrian@iconpln.co.id" },
    { key: "ariefMan", name: "Arief Man", email: "arief.man@iconpln.co.id" },
    { key: "fiqihAlfito", name: "Fiqih Alfito", email: "fiqih.alfito@iconpln.co.id" },
    { key: "vickyaRamadhan", name: "M. Vickya Ramadhan", email: "m.vickya.ramadhan@iconpln.co.id" },
    { key: "herri", name: "Herri", email: "herri@iconpln.co.id" },
    { key: "dbaAaaK1", name: "DBA AAA K1", email: "dba.aaa.k1@iconpln.co.id" },
    { key: "dbaBbbK1", name: "DBA BBB K1", email: "dba.bbb.k1@iconpln.co.id" },
    { key: "devopsAaaK1", name: "Devops AAA K1", email: "devops.aaa.k1@iconpln.co.id" },
    { key: "devopsBbbK1", name: "Devops BBB K1", email: "devops.bbb.k1@iconpln.co.id" },
    { key: "dbaAaaK2", name: "DBA AAA K2", email: "dba.aaa.k2@iconpln.co.id" },
    { key: "dbaBbbK2", name: "DBA BBB K2", email: "dba.bbb.k2@iconpln.co.id" },
    { key: "devopsAaaK2", name: "Devops AAA K2", email: "devops.aaa.k2@iconpln.co.id" },
    { key: "devopsBbbK2", name: "Devops BBB K2", email: "devops.bbb.k2@iconpln.co.id" },
    { key: "dbaAaaK3", name: "DBA AAA K3", email: "dba.aaa.k3@iconpln.co.id" },
    { key: "dbaBbbK3", name: "DBA BBB K3", email: "dba.bbb.k3@iconpln.co.id" },
    { key: "devopsAaaK3", name: "Devops AAA K3", email: "devops.aaa.k3@iconpln.co.id" },
    { key: "devopsBbbK3", name: "Devops BBB K3", email: "devops.bbb.k3@iconpln.co.id" },
    { key: "atasanQonita", name: "Atasan Qonita", email: "atasan.qonita@iconpln.co.id" },
    { key: "qonitaSupport", name: "Qonita support", email: "qonita.support@iconpln.co.id" },
    { key: "aaaSupport", name: "aaa support", email: "aaa.support@iconpln.co.id" },
    { key: "bbbSupport", name: "bbb support", email: "bbb.support@iconpln.co.id" },
];

/**
 * Signs up every user through Better Auth (creates user + account together
 * with password "12345678"), then re-fetches each one from usersTable by
 * email to recover the generated user_id.
 * Returns a key -> userId lookup map, used by every table below that has
 * a userId FK.
 */
async function seedUsersViaAuthClient(): Promise<Record<string, string>> {
    for (const u of userSignUpData) {
        const { error } = await authClient.signUp.email({
            email: u.email,
            name: u.name,
            password: DEFAULT_PASSWORD,
        });
        if (error) {
            throw new Error(`Failed to sign up ${u.email}: ${error.message}`);
        }
    }
    console.log("✓ users signed up via authClient");

    const userMap: Record<string, string> = {};
    for (const u of userSignUpData) {
        const [row] = await db
            .select({ id: usersTable.id })
            .from(usersTable)
            .where(eq(usersTable.email, u.email));
        if (!row) {
            throw new Error(`User not found after sign-up: ${u.email}`);
        }
        userMap[u.key] = row.id;
    }
    return userMap;
}

// =========================================================================
// Organizations
// =========================================================================

const organizationData: typeof organizationsTable.$inferInsert[] = [
    { organizationId: "01a063fa-e4a6-703e-8ecf-7da7cb01ce2c", name: "PLN Icon Plus" },
    { organizationId: "01a063fa-e4a6-703e-8ecf-8003d9a19f78", name: "PLN Pusat" },
    { organizationId: "01a063fa-e4a6-703e-8ecf-8432c1a6eceb", name: "Perusahaan External" },
];

const ORG = {
    plnIconPlus: "01a063fa-e4a6-703e-8ecf-7da7cb01ce2c",
    plnPusat: "01a063fa-e4a6-703e-8ecf-8003d9a19f78",
    perusahaanExternal: "01a063fa-e4a6-703e-8ecf-8432c1a6eceb",
} as const;

// =========================================================================
// Departements
// =========================================================================

function buildDepartementData(USER: Record<string, string>): typeof departementsTable.$inferInsert[] {
    return [
        {
            departementId: "01a063fa-e4a6-703e-8ecf-8b267a3b47e9",
            name: "Digitalisasi PLN 2",
            organizationId: ORG.plnIconPlus,
            userId: USER.hermawanAsmoko,
        },
        {
            departementId: "01a063fa-e4a6-703e-8ecf-8c3b11ace2fe",
            name: "Operasi PLN",
            organizationId: ORG.plnIconPlus,
            userId: USER.fulanVpLain,
        },
        {
            departementId: "01a063fa-e4a6-703e-8ecf-9059fbe14ca8",
            name: "Outsourcing etc",
            organizationId: ORG.perusahaanExternal,
            // no user specified in the requirement for this department
            userId: USER.fulanVpLain,
        },
    ];
}

const DEPT = {
    digitalisasiPln2: "01a063fa-e4a6-703e-8ecf-8b267a3b47e9",
    operasiPln: "01a063fa-e4a6-703e-8ecf-8c3b11ace2fe",
    outsourcingEtc: "01a063fa-e4a6-703e-8ecf-9059fbe14ca8",
} as const;

// =========================================================================
// Sub Departements
// =========================================================================

function buildSubDepartmentData(USER: Record<string, string>): typeof subDepartmentsTable.$inferInsert[] {
    return [
        {
            subDepartmentId: "01a063fa-e4a6-703e-8ecf-94bee3c8e046",
            name: "Aplikasi PLN Korporat dan Pelayanan Pelanggan 1",
            departementId: DEPT.digitalisasiPln2,
            userId: USER.christland,
        },
        {
            subDepartmentId: "01a063fa-e4a6-703e-8ecf-9a45c6bd98f7",
            name: "Aplikasi PLN Korporat dan Pelayanan Pelanggan 2",
            departementId: DEPT.digitalisasiPln2,
            userId: USER.ariefMan,
        },
        {
            subDepartmentId: "01a063fa-e4a6-703e-8ecf-9c7c57033d89",
            name: "Aplikasi PLN Korporat dan Pelayanan Pelanggan 3",
            departementId: DEPT.digitalisasiPln2,
            userId: USER.andrian,
        },
        {
            subDepartmentId: "01a063fa-e4a6-703e-8ecf-a211240e1881",
            name: "PLN Operasi",
            departementId: DEPT.operasiPln,
            userId: USER.atasanQonita,
        },
    ];
}

const SUBDEPT = {
    pelayananPelanggan1: "01a063fa-e4a6-703e-8ecf-94bee3c8e046",
    pelayananPelanggan2: "01a063fa-e4a6-703e-8ecf-9a45c6bd98f7",
    pelayananPelanggan3: "01a063fa-e4a6-703e-8ecf-9c7c57033d89",
    plnOperasi: "01a063fa-e4a6-703e-8ecf-a211240e1881",
} as const;

// =========================================================================
// Teams
// =========================================================================

const teamData: typeof teamsTable.$inferInsert[] = [
    {
        teamId: "01a063fa-e4a6-703e-8ecf-a61c08f5250a",
        name: "Seksi Operasional",
        subDepartmentId: SUBDEPT.pelayananPelanggan1,
    },
    {
        teamId: "01a063fa-e4a6-703e-8ecf-a8f9d623b606",
        name: "Seksi Pengembangan",
        subDepartmentId: SUBDEPT.pelayananPelanggan1,
    },
    {
        teamId: "01a063fa-e4a6-703e-8ecf-ae7257ac25a9",
        name: "Seksi Support Qonita",
        subDepartmentId: SUBDEPT.plnOperasi,
    },
];

const TEAM = {
    seksiOperasional: "01a063fa-e4a6-703e-8ecf-a61c08f5250a",
    seksiPengembangan: "01a063fa-e4a6-703e-8ecf-a8f9d623b606",
    seksiSupportQonita: "01a063fa-e4a6-703e-8ecf-ae7257ac25a9",
} as const;

// =========================================================================
// Sub Teams
// =========================================================================

const subTeamData: typeof subTeamsTable.$inferInsert[] = [
    { subTeamId: "01a063fa-e4a6-703e-8ecf-c37ac34a9664", name: "DBA", teamId: TEAM.seksiOperasional },
    { subTeamId: "01a063fa-e4a6-703e-8ecf-c72fd338bf16", name: "DEVOPS", teamId: TEAM.seksiOperasional },
];

const SUBTEAM = {
    dba: "01a063fa-e4a6-703e-8ecf-c37ac34a9664",
    devops: "01a063fa-e4a6-703e-8ecf-c72fd338bf16",
} as const;

// =========================================================================
// Team Leaders
// =========================================================================

function buildTeamLeaderData(USER: Record<string, string>): typeof teamLeadersTable.$inferInsert[] {
    return [
        {
            teamLeaderId: "01a063fa-e4a6-703e-8ecf-b3c3dd74e66d",
            userId: USER.fiqihAlfito,
            teamId: TEAM.seksiOperasional,
        },
        {
            teamLeaderId: "01a063fa-e4a6-703e-8ecf-b61b9a844a29",
            userId: USER.vickyaRamadhan,
            teamId: TEAM.seksiOperasional,
        },
        {
            teamLeaderId: "01a063fa-e4a6-703e-8ecf-b996b71fdedd",
            userId: USER.herri,
            teamId: TEAM.seksiOperasional,
        },
        {
            teamLeaderId: "01a063fa-e4a6-703e-8ecf-be64606843e8",
            userId: USER.qonitaSupport,
            teamId: TEAM.seksiSupportQonita,
        },
    ];
}

// =========================================================================
// Application Services
// =========================================================================

const applicationServiceData: typeof applicationServicesTable.$inferInsert[] = [
    { applicationServiceId: "01a063fa-e4a6-703e-8ecf-c9a85f85c35c", name: "AMS", subDepartmentId: SUBDEPT.pelayananPelanggan1 },
    { applicationServiceId: "01a063fa-e4a6-703e-8ecf-cce5f1ed59ce", name: "ESPPD", subDepartmentId: SUBDEPT.pelayananPelanggan1 },
    { applicationServiceId: "01a063fa-e4a6-703e-8ecf-d2df473f06bb", name: "PLN Daily", subDepartmentId: SUBDEPT.pelayananPelanggan1 },
];

const APPSVC = {
    ams: "01a063fa-e4a6-703e-8ecf-c9a85f85c35c",
    esppd: "01a063fa-e4a6-703e-8ecf-cce5f1ed59ce",
    plnDaily: "01a063fa-e4a6-703e-8ecf-d2df473f06bb",
} as const;

// =========================================================================
// Team Members
// K1/K2/K3 users -> "Seksi Operasional", role "executioner"
// name starting with "DBA" -> sub_team DBA, "Devops" -> sub_team DEVOPS
// aaa support / bbb support -> "Seksi Support Qonita", role "requester", no sub_team
// =========================================================================

function buildTeamMemberData(USER: Record<string, string>): typeof teamMembersTable.$inferInsert[] {
    return [
        { teamMemberId: "01a063fa-e4a6-703e-8ecf-d785be58ffaf", userId: USER.dbaAaaK1, teamId: TEAM.seksiOperasional, subTeamId: SUBTEAM.dba, roleMember: "executioner" },
        { teamMemberId: "01a063fa-e4a6-703e-8ecf-d83566e4c943", userId: USER.dbaBbbK1, teamId: TEAM.seksiOperasional, subTeamId: SUBTEAM.dba, roleMember: "executioner" },
        { teamMemberId: "01a063fa-e4a6-703e-8ecf-dcc43762ac22", userId: USER.devopsAaaK1, teamId: TEAM.seksiOperasional, subTeamId: SUBTEAM.devops, roleMember: "executioner" },
        { teamMemberId: "01a063fa-e4a6-703e-8ecf-e2415ab62553", userId: USER.devopsBbbK1, teamId: TEAM.seksiOperasional, subTeamId: SUBTEAM.devops, roleMember: "executioner" },
        { teamMemberId: "01a063fa-e4a6-703e-8ecf-e45249c9bd8a", userId: USER.dbaAaaK2, teamId: TEAM.seksiOperasional, subTeamId: SUBTEAM.dba, roleMember: "executioner" },
        { teamMemberId: "01a063fa-e4a6-703e-8ecf-e99dc3a08342", userId: USER.dbaBbbK2, teamId: TEAM.seksiOperasional, subTeamId: SUBTEAM.dba, roleMember: "executioner" },
        { teamMemberId: "01a063fa-e4a6-703e-8ecf-ec84707a262b", userId: USER.devopsAaaK2, teamId: TEAM.seksiOperasional, subTeamId: SUBTEAM.devops, roleMember: "executioner" },
        { teamMemberId: "01a063fa-e4a6-703e-8ecf-f09de2306c1d", userId: USER.devopsBbbK2, teamId: TEAM.seksiOperasional, subTeamId: SUBTEAM.devops, roleMember: "executioner" },
        { teamMemberId: "01a063fa-e4a6-703e-8ecf-f6eccb908735", userId: USER.dbaAaaK3, teamId: TEAM.seksiOperasional, subTeamId: SUBTEAM.dba, roleMember: "executioner" },
        { teamMemberId: "01a063fa-e4a6-703e-8ecf-f933d38e9d9e", userId: USER.dbaBbbK3, teamId: TEAM.seksiOperasional, subTeamId: SUBTEAM.dba, roleMember: "executioner" },
        { teamMemberId: "01a063fa-e4a6-703e-8ecf-ffff55754ad1", userId: USER.devopsAaaK3, teamId: TEAM.seksiOperasional, subTeamId: SUBTEAM.devops, roleMember: "executioner" },
        { teamMemberId: "01a063fa-e4a6-703e-8ed0-03e4d13e0fe8", userId: USER.devopsBbbK3, teamId: TEAM.seksiOperasional, subTeamId: SUBTEAM.devops, roleMember: "executioner" },
        { teamMemberId: "01a063fa-e4a6-703e-8ed0-0491a8a66764", userId: USER.aaaSupport, teamId: TEAM.seksiSupportQonita, subTeamId: null, roleMember: "requester" },
        { teamMemberId: "01a063fa-e4a6-703e-8ed0-0ad6138050b5", userId: USER.bbbSupport, teamId: TEAM.seksiSupportQonita, subTeamId: null, roleMember: "requester" },
    ];
}

// =========================================================================
// Help Topics
// =========================================================================

const helpTopicData: typeof helpTopicsTable.$inferInsert[] = [
    { helpTopicId: "01a063fa-e4a6-703e-8ed0-0fd44cc78150", title: "Perubahan Data", applicationServiceId: APPSVC.ams },
    { helpTopicId: "01a063fa-e4a6-703e-8ed0-135d13fdbcf2", title: "penambahan user", applicationServiceId: APPSVC.ams },
    { helpTopicId: "01a063fa-e4a6-703e-8ed0-149f3e4c8cfc", title: "Perubahan Data", applicationServiceId: APPSVC.esppd },
    { helpTopicId: "01a063fa-e4a6-703e-8ed0-1b193bc1f7be", title: "penambahan user", applicationServiceId: APPSVC.esppd },
    { helpTopicId: "01a063fa-e4a6-703e-8ed0-1ce0f2d3dd07", title: "Perubahan Data", applicationServiceId: APPSVC.plnDaily },
    { helpTopicId: "01a063fa-e4a6-703e-8ed0-205dd159ff2e", title: "penambahan user", applicationServiceId: APPSVC.plnDaily },
];

// =========================================================================
// Seed runner
// insert order follows FK dependency order
// =========================================================================

async function seed() {
    try {
        await truncateAll();
        console.log("Truncated all tables");

        const USER = await seedUsersViaAuthClient();

        await db.insert(organizationsTable).values(organizationData);
        console.log("✓ organizations seeded");

        await db.insert(departementsTable).values(buildDepartementData(USER));
        console.log("✓ departements seeded");

        await db.insert(subDepartmentsTable).values(buildSubDepartmentData(USER));
        console.log("✓ sub_departments seeded");

        await db.insert(teamsTable).values(teamData);
        console.log("✓ teams seeded");

        await db.insert(subTeamsTable).values(subTeamData);
        console.log("✓ sub_teams seeded");

        await db.insert(teamLeadersTable).values(buildTeamLeaderData(USER));
        console.log("✓ team_leaders seeded");

        await db.insert(applicationServicesTable).values(applicationServiceData);
        console.log("✓ application_services seeded");

        await db.insert(teamMembersTable).values(buildTeamMemberData(USER));
        console.log("✓ team_members seeded");

        await db.insert(helpTopicsTable).values(helpTopicData);
        console.log("✓ help_topics seeded");

        console.log("✓ Seed completed");
    } catch (err) {
        console.error("✗ Seed failed:", err);
        process.exit(1);
    }
}

await seed();